Target:
	g++ -std=c++11 conv2d.cpp -o conv2d -lopencv_imgcodecs -lopencv_core -lpthread -g
	g++ -std=c++11 add.cpp -o add -lopencv_imgcodecs -lopencv_core -lpthread -g
	g++ -std=c++11 max_pool.cpp -o max_pool -lopencv_imgcodecs -lopencv_core -lpthread -g
	g++ -std=c++11 avg_pool.cpp -o avg_pool -lopencv_imgcodecs -lopencv_core -lpthread -g
	g++ -std=c++11 batch_norm.cpp -o batch_norm -lopencv_imgcodecs -lopencv_core -lpthread -g
	g++ -std=c++11 dropout.cpp -o dropout -lopencv_imgcodecs -lopencv_core -lpthread -g
	g++ -std=c++11 matmul.cpp -o matmul -lopencv_imgcodecs -lopencv_core -lpthread -g
	g++ -std=c++11 multiply.cpp -o multiply -lopencv_imgcodecs -lopencv_core -lpthread -g
	g++ -std=c++11 relu.cpp -o relu -lopencv_imgcodecs -lopencv_core -lpthread -g
	g++ -std=c++11 sigmoid.cpp -o sigmoid -lopencv_imgcodecs -lopencv_core -lpthread -g
	g++ -std=c++11 softmax.cpp -o softmax -lopencv_imgcodecs -lopencv_core -lpthread -g
	g++ -std=c++11 tanh.cpp -o tanh -lopencv_imgcodecs -lopencv_core -lpthread -g
